pipeline:
  build-and-push:
    image: plugins/docker
    repo: phpdrone/phpdoc
    tags:
      - latest
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      event: push
      branch: master 
