pipeline:
  build-and-push:
    image: plugins/docker
    repo: phpdrone/phpdoc
    build_args:
      - PHPDOC_VERSION=${DRONE_TAG=~2}
    auto_tag: true
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
